// <auto-generated />
using System;
using Kourse_project_BD_vav.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kourse_project_BD_vav.Migrations.Mssql
{
    [DbContext(typeof(MssqlDbContext))]
    [Migration("20251216220734_InitialCreate_Mssql")]
    partial class InitialCreate_Mssql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Client", b =>
                {
                    b.Property<int>("client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("client_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passport_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("registration_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("client_id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Contract", b =>
                {
                    b.Property<int>("contract_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contract_id"));

                    b.Property<DateTime>("contract_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("contract_file")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("deal_id")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("contract_id");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Deal", b =>
                {
                    b.Property<int>("deal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deal_id"));

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("deal_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("deal_price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("deal_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("deal_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("property_id")
                        .HasColumnType("int");

                    b.Property<int?>("realtor_id")
                        .HasColumnType("int");

                    b.HasKey("deal_id");

                    b.HasIndex("client_id");

                    b.HasIndex("property_id");

                    b.HasIndex("realtor_id");

                    b.ToTable("Deals", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Favorite", b =>
                {
                    b.Property<int>("favorite_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("favorite_id"));

                    b.Property<DateTime>("added_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("added_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("property_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("favorite_id");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Property", b =>
                {
                    b.Property<int>("property_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("property_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("area")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("floor")
                        .HasColumnType("int");

                    b.Property<string>("image_urls")
                        .HasColumnType("text");

                    b.Property<bool>("is_available")
                        .HasColumnType("bit");

                    b.Property<string>("main_image_url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("property_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("realtor_id")
                        .HasColumnType("int");

                    b.Property<int?>("rooms")
                        .HasColumnType("int");

                    b.Property<int?>("total_floors")
                        .HasColumnType("int");

                    b.HasKey("property_id");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.PropertyReservation", b =>
                {
                    b.Property<int>("reservation_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reservation_id"));

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("property_id")
                        .HasColumnType("int");

                    b.Property<int?>("realtor_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("reservation_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("reservation_id");

                    b.ToTable("PropertyReservations", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Realtor", b =>
                {
                    b.Property<int>("realtor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("realtor_id"));

                    b.Property<decimal>("commission_rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("hire_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("realtor_id");

                    b.HasIndex("user_id");

                    b.ToTable("Realtors", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("user_id"));

                    b.Property<int?>("client_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("realtor_id")
                        .HasColumnType("int");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("user_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.UserActivity", b =>
                {
                    b.Property<int>("activity_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("activity_id"));

                    b.Property<string>("activity_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("activity_id");

                    b.ToTable("UserActivities", (string)null);
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Deal", b =>
                {
                    b.HasOne("Kourse_project_BD_vav.Models.Client", "client")
                        .WithMany()
                        .HasForeignKey("client_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kourse_project_BD_vav.Models.Property", "property")
                        .WithMany()
                        .HasForeignKey("property_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kourse_project_BD_vav.Models.Realtor", "realtor")
                        .WithMany()
                        .HasForeignKey("realtor_id");

                    b.Navigation("client");

                    b.Navigation("property");

                    b.Navigation("realtor");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Realtor", b =>
                {
                    b.HasOne("Kourse_project_BD_vav.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
