--docker exec -it oracle-xe sqlplus PAACORE/"Password123!"@localhost:1521/XEPDB1

--изменения параметров сессии перед созданием любых объектов
ALTER SESSION SET "_oracle_script" = TRUE;


CREATE TABLESPACE TS_PAA DATAFILE 'TS_PAA.dbf' SIZE 7M AUTOEXTEND ON NEXT 5M MAXSIZE 30M;
CREATE TEMPORARY TABLESPACE TS_PAA_TEMP TEMPFILE 'TS_PAA_TEMP.dbf' SIZE 5M AUTOEXTEND ON NEXT 3M MAXSIZE 20M;

SELECT TABLESPACE_NAME FROM DBA_TABLESPACES;    

SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES UNION ALL
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_TEMP_FILES;

CREATE ROLE RL_PAACORE;
GRANT CREATE SESSION TO RL_PAACORE;
GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO RL_PAACORE;

SELECT ROLE FROM DBA_ROLES WHERE ROLE = 'RL_PAACORE';
SELECT PRIVILEGE FROM ROLE_SYS_PRIVS WHERE ROLE = 'RL_PAACORE';

CREATE PROFILE PF_PAACORE LIMIT 
  PASSWORD_LIFE_TIME 180 SESSIONS_PER_USER 3 FAILED_LOGIN_ATTEMPTS 7 
  PASSWORD_LOCK_TIME 1 PASSWORD_REUSE_TIME 10 PASSWORD_GRACE_TIME 7 
  CONNECT_TIME 180 IDLE_TIME 30;

SELECT DISTINCT PROFILE FROM DBA_PROFILES;
SELECT RESOURCE_NAME, LIMIT FROM DBA_PROFILES WHERE PROFILE = 'PF_PAACORE';
SELECT RESOURCE_NAME, LIMIT FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

CREATE USER PAACORE IDENTIFIED BY "Paacore_123" 
DEFAULT TABLESPACE TS_PAA TEMPORARY TABLESPACE TS_PAA_TEMP 
PROFILE PF_PAACORE ACCOUNT UNLOCK PASSWORD EXPIRE;

GRANT RL_PAACORE TO PAACORE;



------------------------------
ALTER SESSION SET "_oracle_script" = TRUE;
ALTER USER PAACORE QUOTA 2M ON TS_PAA;

------------------------------
ALTER TABLESPACE TS_PAA OFFLINE;
------------------------------
ALTER TABLESPACE TS_PAA ONLINE;