// <auto-generated />
using System;
using Kourse_project_BD_vav.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kourse_project_BD_vav.Migrations.Pg
{
    [DbContext(typeof(PgDbContext))]
    partial class PgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Client", b =>
                {
                    b.Property<int>("client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("client_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("passport_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("registration_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("client_id");

                    b.ToTable("clients", "public");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Contract", b =>
                {
                    b.Property<int>("contract_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("contract_id"));

                    b.Property<DateTime>("contract_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("contract_file")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("deal_id")
                        .HasColumnType("integer");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("contract_id");

                    b.ToTable("contracts", "public");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Deal", b =>
                {
                    b.Property<int>("deal_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("deal_id"));

                    b.Property<int>("client_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("deal_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("deal_price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("deal_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("deal_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("property_id")
                        .HasColumnType("integer");

                    b.Property<int?>("realtor_id")
                        .HasColumnType("integer");

                    b.HasKey("deal_id");

                    b.HasIndex("client_id");

                    b.HasIndex("property_id");

                    b.HasIndex("realtor_id");

                    b.ToTable("deals", "public");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Favorite", b =>
                {
                    b.Property<int>("favorite_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("favorite_id"));

                    b.Property<DateTime>("added_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("added_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("property_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("favorite_id");

                    b.ToTable("favorites", "public");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Property", b =>
                {
                    b.Property<int>("property_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("property_id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("area")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("floor")
                        .HasColumnType("integer");

                    b.Property<string>("image_urls")
                        .HasColumnType("text");

                    b.Property<bool>("is_available")
                        .HasColumnType("boolean");

                    b.Property<string>("main_image_url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("price")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("property_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("realtor_id")
                        .HasColumnType("integer");

                    b.Property<int?>("rooms")
                        .HasColumnType("integer");

                    b.Property<int?>("total_floors")
                        .HasColumnType("integer");

                    b.HasKey("property_id");

                    b.ToTable("properties", "public");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Realtor", b =>
                {
                    b.Property<int>("realtor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("realtor_id"));

                    b.Property<decimal>("commission_rate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("hire_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("realtor_id");

                    b.HasIndex("user_id");

                    b.ToTable("realtors", "public");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<int?>("client_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("realtor_id")
                        .HasColumnType("integer");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("user_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Deal", b =>
                {
                    b.HasOne("Kourse_project_BD_vav.Models.Client", "client")
                        .WithMany()
                        .HasForeignKey("client_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kourse_project_BD_vav.Models.Property", "property")
                        .WithMany()
                        .HasForeignKey("property_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kourse_project_BD_vav.Models.Realtor", "realtor")
                        .WithMany()
                        .HasForeignKey("realtor_id");

                    b.Navigation("client");

                    b.Navigation("property");

                    b.Navigation("realtor");
                });

            modelBuilder.Entity("Kourse_project_BD_vav.Models.Realtor", b =>
                {
                    b.HasOne("Kourse_project_BD_vav.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
