CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE public.clients (
    client_id integer GENERATED BY DEFAULT AS IDENTITY,
    full_name character varying(100) NOT NULL,
    phone_number character varying(20) NOT NULL,
    email character varying(100) NOT NULL,
    passport_number character varying(20) NOT NULL,
    registration_date timestamp with time zone NOT NULL DEFAULT (CURRENT_DATE),
    user_id integer,
    CONSTRAINT "PK_clients" PRIMARY KEY (client_id)
);

CREATE TABLE public.contracts (
    contract_id integer GENERATED BY DEFAULT AS IDENTITY,
    deal_id integer NOT NULL,
    contract_date timestamp with time zone NOT NULL,
    contract_file character varying(255) NOT NULL,
    notes text NOT NULL,
    CONSTRAINT "PK_contracts" PRIMARY KEY (contract_id)
);

CREATE TABLE public.favorites (
    favorite_id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    property_id integer NOT NULL,
    added_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    added_date timestamp with time zone NOT NULL,
    CONSTRAINT "PK_favorites" PRIMARY KEY (favorite_id)
);

CREATE TABLE public.properties (
    property_id integer GENERATED BY DEFAULT AS IDENTITY,
    address character varying(255) NOT NULL,
    property_type character varying(50) NOT NULL,
    area numeric(10,2) NOT NULL,
    price numeric(15,2) NOT NULL,
    description text NOT NULL,
    realtor_id integer,
    is_available boolean NOT NULL,
    main_image_url character varying(500),
    image_urls text,
    rooms integer,
    floor integer,
    total_floors integer,
    CONSTRAINT "PK_properties" PRIMARY KEY (property_id)
);

CREATE TABLE public.users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(50) NOT NULL,
    password_hash character varying(255) NOT NULL,
    email character varying(100) NOT NULL,
    full_name character varying(100) NOT NULL,
    role character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    client_id integer,
    realtor_id integer,
    CONSTRAINT "PK_users" PRIMARY KEY (user_id)
);

CREATE TABLE public.realtors (
    realtor_id integer GENERATED BY DEFAULT AS IDENTITY,
    full_name character varying(100) NOT NULL,
    phone_number character varying(20) NOT NULL,
    email character varying(100) NOT NULL,
    hire_date timestamp with time zone NOT NULL DEFAULT (CURRENT_DATE),
    commission_rate numeric(5,2) NOT NULL,
    user_id integer,
    CONSTRAINT "PK_realtors" PRIMARY KEY (realtor_id),
    CONSTRAINT "FK_realtors_users_user_id" FOREIGN KEY (user_id) REFERENCES public.users (user_id)
);

CREATE TABLE public.deals (
    deal_id integer GENERATED BY DEFAULT AS IDENTITY,
    property_id integer NOT NULL,
    client_id integer NOT NULL,
    realtor_id integer,
    deal_type character varying(50) NOT NULL,
    deal_status character varying(50) NOT NULL,
    deal_date timestamp with time zone NOT NULL,
    deal_price numeric(15,2) NOT NULL,
    CONSTRAINT "PK_deals" PRIMARY KEY (deal_id),
    CONSTRAINT "FK_deals_clients_client_id" FOREIGN KEY (client_id) REFERENCES public.clients (client_id) ON DELETE CASCADE,
    CONSTRAINT "FK_deals_properties_property_id" FOREIGN KEY (property_id) REFERENCES public.properties (property_id) ON DELETE CASCADE,
    CONSTRAINT "FK_deals_realtors_realtor_id" FOREIGN KEY (realtor_id) REFERENCES public.realtors (realtor_id)
);

CREATE INDEX "IX_deals_client_id" ON public.deals (client_id);

CREATE INDEX "IX_deals_property_id" ON public.deals (property_id);

CREATE INDEX "IX_deals_realtor_id" ON public.deals (realtor_id);

CREATE INDEX "IX_realtors_user_id" ON public.realtors (user_id);

CREATE UNIQUE INDEX "IX_users_email" ON public.users (email);

CREATE UNIQUE INDEX "IX_users_username" ON public.users (username);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251216220803_InitialCreate_Pg', '8.0.0');

COMMIT;

